$k='alloy_f61ae87aa276580b46fdcdaa5fbcd0a98792e34a737be989a796c9f8bf7a6256'
$bodyU = Join-Path $PSScriptRoot 'body-url.json'
$bodyD = Join-Path $PSScriptRoot 'body-domain.json'

Write-Host '--- POST /api/url/meta (file)'
& curl.exe -sS -X POST -H "x-api-key: $k" -H 'Content-Type: application/json' --data-binary "@$bodyU" 'https://api.connormerk.dev/api/url/meta'
Write-Host ''
Write-Host '--- POST /api/security/headers (file)'
& curl.exe -sS -X POST -H "x-api-key: $k" -H 'Content-Type: application/json' --data-binary "@$bodyU" 'https://api.connormerk.dev/api/security/headers'
Write-Host ''
Write-Host '--- POST /api/security/url (file)'
& curl.exe -sS -X POST -H "x-api-key: $k" -H 'Content-Type: application/json' --data-binary "@$bodyU" 'https://api.connormerk.dev/api/security/url'
Write-Host ''
Write-Host '--- POST /api/internet/diagnose (file)'
& curl.exe -sS -X POST -H "x-api-key: $k" -H 'Content-Type: application/json' --data-binary "@$bodyD" 'https://api.connormerk.dev/api/internet/diagnose'
