$k='alloy_f61ae87aa276580b46fdcdaa5fbcd0a98792e34a737be989a796c9f8bf7a6256'

Write-Host '--- POST /api/url/meta'
& curl.exe -sS -X POST -H "x-api-key: $k" -H 'Content-Type: application/json' -d '{"url":"https://cloudflare.com"}' 'https://api.connormerk.dev/api/url/meta'
Write-Host ''
Write-Host '--- POST /api/internet/diagnose'
& curl.exe -sS -X POST -H "x-api-key: $k" -H 'Content-Type: application/json' -d '{"domain":"cloudflare.com"}' 'https://api.connormerk.dev/api/internet/diagnose'
Write-Host ''
Write-Host '--- GET ?url= via header X-Url'
& curl.exe -sS -H "x-api-key: $k" -H 'X-Url: https://cloudflare.com' 'https://api.connormerk.dev/api/url/meta'
Write-Host ''
Write-Host '--- using ?URL= uppercase'
& curl.exe -sS -H "x-api-key: $k" 'https://api.connormerk.dev/api/url/meta?URL=https%3A%2F%2Fcloudflare.com'
Write-Host ''
Write-Host '--- /api/url/meta?link='
& curl.exe -sS -H "x-api-key: $k" 'https://api.connormerk.dev/api/url/meta?link=https%3A%2F%2Fcloudflare.com'
Write-Host ''
Write-Host '--- OPTIONS /api/url/meta'
& curl.exe -sS -X OPTIONS -H "x-api-key: $k" 'https://api.connormerk.dev/api/url/meta'
